### ISSUE TITLE
Override Print::write(const uint8_t *buffer, size_t size)

### ISSUE THREAD

**Issue by tig** [RobTillaart/Multiplex#4]
Felt slow. 

Then I noticed you only overrode `write(uint8_t c)` on `Print`, so when using `EthenetClient` as my stream each char gets sent one at a time vs. using `EthernetClient`'s buffers.

The fix is to override `virtual size_t write(const uint8_t *buffer, size_t size)` from `Print`.

PR incoming...

**Comment by RobTillaart** [comment]
fixed in 0.2.0
